# This is a basic workflow to help you get started with Actions
# https://www.youtube.com/watch?v=1npWH0rPOnI
# https://github.com/marketplace/actions/deploy-your-app-to-github-pages
name: gh-pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build
      - name: GitHub Pages
        # You may pin to the exact commit or the version.
        # uses: crazy-max/ghaction-github-pages@db4476a01402e1a7ce05f41832040eef16d14925
        uses: crazy-max/ghaction-github-pages@v2.5.0
        env:
          GH_PAT: ${{ secrets.PA_TOKEN }}
        with:
          # Git domain (default github.com)
          domain:  github.com # optional, default is github.com
          # GitHub repository where assets will be deployed (default $GITHUB_REPOSITORY)
          repo: $GITHUB_REPOSITORY # optional
          # Git branch where assets will be deployed
          target_branch: gh-pages # optional, default is gh-pages
          # Build directory to deploy
          build_dir: .
          # Enable verbose output
          verbose: false# optional, default is false




